eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
server:
  port: 8763
spring:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  application:
    name: serviceuser
  cloud:
    client:
      ipAddress: eurekaserver
    config:
      discovery:
        enabled: true
        service-id: springcloud-config
      profile: dev
userinfo:
  username: sxx
  password: 11111232323
