eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: serviceuser
userinfo:
  username: sxx
  password: 12345678
