eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.247.131:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: serviceuser
  rabbitmq:
    host: 192.168.1.5
    port: 5672
    username: guest
    password: guest
userinfo:
  username: fsq
  password: 12345678
