eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.247.130:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: serviceuser
userinfo:
  username: sxx
  password: 1345
